# Mathematical Formulas

This is a concise demonstration of mathematical functionality in Julia. We'll need to use `Gadfly` for some graphing.

## Install & Import Gadfly
Note: Gadfly can take a while to install and then a while to precompile.

In [1]:
using Pkg
Pkg.add("Gadfly")

   Updating registry at `~/.julia/registries/General`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`


In [2]:
using Gadfly

## Math Functions
Julia has all the usual math functions.

In [4]:

x =  sin(exp(atan(1,2)))

0.9998182437676517

In [5]:
z = 0.0+1.0im

0.0 + 1.0im

In [6]:
real(z)

0.0

Because type stability is very important for performance some functions will not switch automatically to complex numbers.

In [7]:
sqrt(-1)

LoadError: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [8]:
sqrt(complex(-1))

0.0 + 1.0im

There are also special mathematical functions, such as the [Zeta function](http://math.stackexchange.com/questions/157045/explanation-of-zeta-function-and-why-1234-1-12)

In [9]:
zeta(-1)

LoadError: UndefVarError: zeta not defined

Fourier transform.

In [10]:
f = zeros(101)
f[51] = 1 
F = fft(f)

plot(x=collect(1:101), y=real(F))

LoadError: UndefVarError: fft not defined

Integers can overflow if you're not careful.

In [11]:
10^40

-5047021154770878464

But you can get integers with arbitrary precision using `BigInt`.

In [12]:
BigInt(10)^40

10000000000000000000000000000000000000000

## Matrix functions

In [13]:
A = rand(5,5)

5×5 Array{Float64,2}:
 0.962697  0.0950551  0.0501852  0.732542  0.983194
 0.351531  0.0731243  0.5797     0.397478  0.945303
 0.118232  0.205102   0.041537   0.666288  0.365704
 0.096654  0.836662   0.286695   0.772794  0.511593
 0.636733  0.390808   0.638605   0.71303   0.536199

Get the determinant of a matrix.

In [14]:
det(A)

LoadError: UndefVarError: det not defined

Matrix multiplication.

In [15]:
b = rand(2,5)

2×5 Array{Float64,2}:
 0.16833   0.959199  0.421141  0.896081  0.701641
 0.613447  0.160451  0.669877  0.342143  0.321627

In [16]:
b*A

2×5 Array{Float64,2}:
 1.0824    1.19644  1.28696   1.97795  2.0609
 0.964028  0.61939  0.455107  1.45322  1.34728

Show A in the sparse matrix format.

In [17]:
sparse(A)

LoadError: UndefVarError: sparse not defined

## A more complicated example
Compute the eigenfunctions of the diffusion operator (second derivative).

In [19]:
N = 200
A = zeros(N,N)
δx = 2*pi/N

for i=2:N-1
    A[i,i] = -2
    A[i,i+1] = 1
    A[i,i-1] = 1
end

Set the boundary conditions.

In [20]:
A[1,1] = -2; A[1,2] = 1; A[1,N] = 1
A[N,N] = -2; A[N,N-1] = 1; A[N,1] = 1

1

Element wise operation.

In [21]:
A = A ./ δx^2

200×200 Array{Float64,2}:
 -2026.42   1013.21      0.0       0.0   …      0.0       0.0    1013.21
  1013.21  -2026.42   1013.21      0.0          0.0       0.0       0.0
     0.0    1013.21  -2026.42   1013.21         0.0       0.0       0.0
     0.0       0.0    1013.21  -2026.42         0.0       0.0       0.0
     0.0       0.0       0.0    1013.21         0.0       0.0       0.0
     0.0       0.0       0.0       0.0   …      0.0       0.0       0.0
     0.0       0.0       0.0       0.0          0.0       0.0       0.0
     0.0       0.0       0.0       0.0          0.0       0.0       0.0
     0.0       0.0       0.0       0.0          0.0       0.0       0.0
     0.0       0.0       0.0       0.0          0.0       0.0       0.0
     0.0       0.0       0.0       0.0   …      0.0       0.0       0.0
     0.0       0.0       0.0       0.0          0.0       0.0       0.0
     0.0       0.0       0.0       0.0          0.0       0.0       0.0
     ⋮                               

Compute the eigenvalue (d) and eigenvectors (v).

In [22]:
d,v = eig(A)

LoadError: UndefVarError: eig not defined

Make a quick plot.

In [23]:
plot(x=collect(1:N),y=v[:,N-1])

LoadError: UndefVarError: v not defined

d²/dx² sin(x) = λ sin(x) with λ = -1

In [24]:
d[N-1]

LoadError: UndefVarError: d not defined

And d²/dx² sin(2x) = λ sin(2x)

In [25]:
plot(x=collect(1:N),y=v[:,N-3])

LoadError: UndefVarError: v not defined